"""empty message

Revision ID: 45a739aa5394
Revises: d25704751918
Create Date: 2020-04-01 12:17:30.839741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a739aa5394'
down_revision = 'd25704751918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_drugs',
    sa.Column('treatment_id', sa.Integer(), nullable=True),
    sa.Column('drug_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treatment_drugs')
    # ### end Alembic commands ###
