"""empty message

Revision ID: 779f7fe6d8e8
Revises: ed7eead1e90d
Create Date: 2020-04-02 23:02:08.567008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779f7fe6d8e8'
down_revision = 'ed7eead1e90d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=180), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
