"""empty message

Revision ID: d25704751918
Revises: ded5a139f941
Create Date: 2020-04-01 10:27:41.890151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25704751918'
down_revision = 'ded5a139f941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=180), nullable=True),
    sa.Column('second_name', sa.String(length=180), nullable=True),
    sa.Column('third_name', sa.String(length=180), nullable=True),
    sa.Column('kp_code', sa.String(length=180), nullable=True),
    sa.Column('gender', sa.String(length=180), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('kp_hotspot_site', sa.String(length=180), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('employed', sa.Boolean(), nullable=True),
    sa.Column('occupation', sa.String(length=180), nullable=True),
    sa.Column('relationship_status', sa.String(length=180), nullable=True),
    sa.Column('education_level', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=180), nullable=True),
    sa.Column('category', sa.String(length=180), nullable=True),
    sa.Column('type_of_syndrome', sa.String(length=180), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('new_client', sa.Boolean(), nullable=True),
    sa.Column('bp', sa.String(length=180), nullable=True),
    sa.Column('weight', sa.String(length=180), nullable=True),
    sa.Column('refered_to_other_facility', sa.Boolean(), nullable=True),
    sa.Column('facility_refered_to', sa.String(length=180), nullable=True),
    sa.Column('condom_given', sa.Boolean(), nullable=True),
    sa.Column('lubricant_given', sa.Boolean(), nullable=True),
    sa.Column('date_of_next_visit', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.String(length=180), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treatments')
    op.drop_table('patients')
    op.drop_table('drugs')
    # ### end Alembic commands ###
